### ISSUE TITLE
Import/Export as yaml/toml

### ISSUE THREAD

**Issue by alexanderjophus** [alexanderjophus/wasme#3]
A user should be able to share a setup, and/or have an easy way to save it for next time.

```toml
[modes.inverted.v1]
enabled = true
[modes.pixelate.v1]
enabled = true
block_size = 10
```

Should set enable the user to see a inverted then pixelated video feed.
